# Generated by Django 5.2.5 on 2025-08-21 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('caracteristicas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('explicacao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Dificuldade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('explicacao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('explicacao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('nivel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vantagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('explicacao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackFaceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('nivel', models.IntegerField()),
                ('conclusao', models.TextField()),
                ('caracteristicas', models.ManyToManyField(to='bigfive.caracteristica')),
                ('dificuldades', models.ManyToManyField(to='bigfive.dificuldade')),
                ('estrategias', models.ManyToManyField(to='bigfive.estrategia')),
                ('vantagens', models.ManyToManyField(to='bigfive.vantagem')),
            ],
        ),
        migrations.CreateModel(
            name='Faceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigfive.area')),
                ('feedbacks', models.ManyToManyField(to='bigfive.feedbackfaceta')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('isReversa', models.BooleanField(default=False)),
                ('faceta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigfive.faceta')),
                ('feedbacks', models.ManyToManyField(to='bigfive.feedbackpergunta')),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grau', models.CharField(choices=[('docente', 'Docente'), ('discente', 'Discente')], max_length=10)),
                ('areas', models.ManyToManyField(to='bigfive.area')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigfive.centro')),
                ('perguntas', models.ManyToManyField(to='bigfive.pergunta')),
            ],
        ),
    ]
