# Generated by Django 5.2.5 on 2025-08-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=100)),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("pontuacao", models.FloatField()),
            ],
        ),
    ]
