# Generated by Django 5.2.5 on 2025-08-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigfive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('nota_min', models.FloatField()),
                ('nota_max', models.FloatField()),
            ],
        ),
    ]
