# Generated by Django 5.2.5 on 2025-08-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigfive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro', models.CharField(max_length=100)),
                ('areas', models.ManyToManyField(to='bigfive.area')),
                ('perguntas', models.ManyToManyField(to='bigfive.pergunta')),
            ],
        ),
    ]
