# Generated by Django 5.2.5 on 2025-08-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigfive', '0002_nivelamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelamento',
            name='num_nivel',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
